version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend  # Points to the backend directory
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Correct path to main.py
    volumes:
      - ./backend:/app  # Mount the backend folder to /code in the container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 333:80
    depends_on:
      - database
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge