"""new_rental_status_

Revision ID: f8c9d654fde8
Revises: c9ac2f0e609e
Create Date: 2024-12-22 15:04:42.172890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'f8c9d654fde8'
down_revision: Union[str, None] = 'c9ac2f0e609e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_locks_ip', 'locks', ['ip'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_locks_ip', 'locks', type_='unique')
    # ### end Alembic commands ###
